### ISSUE TITLE
Deno or Node.js + TSで再実装したい

### ISSUE THREAD

**Issue by arrow2nd** [arrow2nd/linebot-imas#85]
- 型がなくてメンテナンスしにくい
- npmサポートでSDKが動くかもしれない！

**Comment by arrow2nd** [comment]
> DenoでLINEのSDKが動くかも

動きませんでした…

```
Error: Not implemented: crypto.Hmac
    at notImplemented (https://deno.land/std@0.164.0/node/_utils.ts:23:9)
    at new Hmac (https://deno.land/std@0.164.0/node/internal/crypto/hash.ts:139:5)
    at Object.createHmac (https://deno.land/std@0.164.0/node/crypto.ts:264:10)
    at Object.validateSignature [as default] (file:///Users/arrow2nd/Library/Caches/deno/npm/registry.npmjs.org/@line/bot-sdk/7.5.2/dist/validate-signature.js
:14:33)
    at _middleware (file:///Users/arrow2nd/Library/Caches/deno/npm/registry.npmjs.org/@line/bot-sdk/7.5.2/dist/middleware.js:36:42)
    at Object.runMicrotasks (deno:core/01_core.js:377:30)
    at processTicksAndRejections (https://deno.land/std@0.164.0/node/_next_tick.ts:62:10)
```
